name: lab9.2

on:
  push:
  
jobs:
    work:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
            git submodule update --init --recursive
            cmake -B ./output
            cd output
            make
        - name: upload artifacts
          uses: actions/upload-artifact@v3
          with:
           name: banking
           path: |
            ./banking
        - name: download artifacts
          with:
           name: banking
           path: ./artifact
          
           
       
        
            
